language: ruby
rvm:
  - 2.3.1
  - 2.2
services:
  - postresql
env:
  global:
    - DATABASE_URL=postgresql://localhost:5432/noteworthy_test?pool=5
    - GOOGLE_CLIENT_ID=fake-client-id
    - GOOGLE_CLIENT_SECRET=fake-client-secret
    - APPLICATION_BASE_URL=noteworthy.dev
before_script:
  - psql -c 'create database noteworthy_test;' -U postgres
