language: ruby
rvm:
  - 2.3.1
  - 2.2
addons:
  postgresql: "9.6"
services:
  - postresql
env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost:5432/noteworthy_test?pool=5
    - GOOGLE_CLIENT_ID=fake-client-id
    - GOOGLE_CLIENT_SECRET=fake-client-secret
    - APPLICATION_BASE_URL=noteworthy.dev
before_script:
  - psql -U postgres -c 'create database noteworthy_test;'
  - psql -U postgres -c 'create extension pgcrypto;'
  - bin/rails db:migrate RAILS_ENV=test
